# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    App\Controller\Controller:
        arguments:
            - '%kernel.cache_dir%'
        autoconfigure: true

    App\Baldinof\RoadRunnerBundle\HttpFoundationWorker:
        arguments:
            - '@Spiral\RoadRunner\Http\HttpWorkerInterface'

    App\Baldinof\RoadRunnerBundle\UseFixedHttpFoundationWorker:
        decorates: Baldinof\RoadRunnerBundle\RoadRunnerBridge\HttpFoundationWorkerInterface
        arguments:
            - '@.inner'
            - '@App\Baldinof\RoadRunnerBundle\HttpFoundationWorker'
            - '%env(bool:USE_FIXED_BALDINOF_RR)%'
